//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cemu.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj katedru.
        /// </summary>
        internal static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj profesora.
        /// </summary>
        internal static string AddProfessor {
            get {
                return ResourceManager.GetString("AddProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj predmet profesoru.
        /// </summary>
        internal static string AddProfessorToSubject {
            get {
                return ResourceManager.GetString("AddProfessorToSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj studenta.
        /// </summary>
        internal static string AddStudent {
            get {
                return ResourceManager.GetString("AddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj predmet.
        /// </summary>
        internal static string AddSubject {
            get {
                return ResourceManager.GetString("AddSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        internal static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosek.
        /// </summary>
        internal static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosecna ocena:.
        /// </summary>
        internal static string Average_grade {
            get {
                return ResourceManager.GetString("Average grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavi sefa.
        /// </summary>
        internal static string Chose_Manager {
            get {
                return ResourceManager.GetString("Chose Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi predmet.
        /// </summary>
        internal static string Chose_subject {
            get {
                return ResourceManager.GetString("Chose subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra predmeta.
        /// </summary>
        internal static string Course_code {
            get {
                return ResourceManager.GetString("Course code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna godina.
        /// </summary>
        internal static string Current_year_of_study {
            get {
                return ResourceManager.GetString("Current year of study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rodjenja.
        /// </summary>
        internal static string Date_of_birth {
            get {
                return ResourceManager.GetString("Date of birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum polaganja.
        /// </summary>
        internal static string Date_of_taking_exam {
            get {
                return ResourceManager.GetString("Date of taking exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrisi.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponisti ocenu.
        /// </summary>
        internal static string Delete_grade {
            get {
                return ResourceManager.GetString("Delete grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra katedre.
        /// </summary>
        internal static string Department_code {
            get {
                return ResourceManager.GetString("Department code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katedre.
        /// </summary>
        internal static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESPB.
        /// </summary>
        internal static string ECTS {
            get {
                return ResourceManager.GetString("ECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma ESPB:.
        /// </summary>
        internal static string ECTS_sum {
            get {
                return ResourceManager.GetString("ECTS sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena katedre.
        /// </summary>
        internal static string EditDepartment {
            get {
                return ResourceManager.GetString("EditDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena profesora.
        /// </summary>
        internal static string EditProfessor {
            get {
                return ResourceManager.GetString("EditProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena studenta.
        /// </summary>
        internal static string EditStudent {
            get {
                return ResourceManager.GetString("EditStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena predmeta.
        /// </summary>
        internal static string EditSubject {
            get {
                return ResourceManager.GetString("EditSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polaganje.
        /// </summary>
        internal static string Exam {
            get {
                return ResourceManager.GetString("Exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepolozeni.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fajl.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena.
        /// </summary>
        internal static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra predmeta.
        /// </summary>
        internal static string Grade_code {
            get {
                return ResourceManager.GetString("Grade code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv predmeta.
        /// </summary>
        internal static string Grade_title {
            get {
                return ResourceManager.GetString("Grade title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoc.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj licne karte.
        /// </summary>
        internal static string IdCard {
            get {
                return ResourceManager.GetString("IdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj Licne Karte.
        /// </summary>
        internal static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj Indeksa (npr: RA-110/2020).
        /// </summary>
        internal static string Index_Number__exp__RA_110_2020_ {
            get {
                return ResourceManager.GetString("Index Number (exp: RA-110/2020)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije.
        /// </summary>
        internal static string Informations {
            get {
                return ResourceManager.GetString("Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizacija.
        /// </summary>
        internal static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sef.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv katedre.
        /// </summary>
        internal static string Name_of_Department {
            get {
                return ResourceManager.GetString("Name of Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvori.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polozio.
        /// </summary>
        internal static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polozio predmet.
        /// </summary>
        internal static string PassExam {
            get {
                return ResourceManager.GetString("PassExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime profesora.
        /// </summary>
        internal static string Professor_Name {
            get {
                return ResourceManager.GetString("Professor Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id profesora.
        /// </summary>
        internal static string ProfessorId {
            get {
                return ResourceManager.GetString("ProfessorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesori.
        /// </summary>
        internal static string Professors {
            get {
                return ResourceManager.GetString("Professors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacuvaj.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestar.
        /// </summary>
        internal static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        internal static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizacija primjer.
        /// </summary>
        internal static string StatusBarString {
            get {
                return ResourceManager.GetString("StatusBarString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string statusDate {
            get {
                return ResourceManager.GetString("statusDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartica.
        /// </summary>
        internal static string statusTab {
            get {
                return ResourceManager.GetString("statusTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme.
        /// </summary>
        internal static string statusTime {
            get {
                return ResourceManager.GetString("statusTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status studenta.
        /// </summary>
        internal static string Student_status {
            get {
                return ResourceManager.GetString("Student status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenti.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmet.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra predmeta.
        /// </summary>
        internal static string Subject_code {
            get {
                return ResourceManager.GetString("Subject code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmeti.
        /// </summary>
        internal static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prozor.
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godine staza.
        /// </summary>
        internal static string Year_of_experience {
            get {
                return ResourceManager.GetString("Year of experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina Studija.
        /// </summary>
        internal static string Year_of_study {
            get {
                return ResourceManager.GetString("Year of study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
